<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Sample.Library</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Testing.Abstractions\Testing.Abstractions.csproj" />
  </ItemGroup>

</Project>
